### ISSUE TITLE
ImportError: cannot import name 'Queue' from 'distributed.compatibility'

### ISSUE THREAD

**Issue by ghost** [mrocklin/dask-tensorflow#11]
When I try to do the following: 
`from dask_tensorflow import start _tensorflow`
I get the following error: 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-d8ae128e04b2> in <module>
----> 1 from dask_tensorflow import start_tensorflow

~/anaconda3/lib/python3.7/site-packages/dask_tensorflow/__init__.py in <module>
----> 1 from .core import _start_tensorflow, start_tensorflow
      2 
      3 __version__ = '0.0.2'

~/anaconda3/lib/python3.7/site-packages/dask_tensorflow/core.py in <module>
      4 from tornado import gen
      5 
----> 6 from distributed.compatibility import Queue
      7 from distributed.utils import sync
      8 import tensorflow as tf

ImportError: cannot import name 'Queue' from 'distributed.compatibility' (/home/vinhdiesal/anaconda3/lib/python3.7/site-packages/distributed/compatibility.py)
```

**Comment by TomAugspurger** [comment]
You probably don't want to use this module.

@mrocklin any objection to archiving dask-tensorflow?

**Comment by ghost** [comment]
Does this mean there's no way to use tensorflow in a dask-cluster and instead we have to use the tensorflow's built in distributed mirror strategies?

**Comment by mrocklin** [comment]
No objections from me

**Comment by mrocklin** [comment]
There are still many ways to use tensorflow and Dask together, just not
this particular way

**Comment by ghost** [comment]
Before I close, can you provide an example or tutorial on how to combine tensorflow and Dask together?
I want to accomplish tensorflow on an existing DASK ssh cluster.

**Comment by mrocklin** [comment]
Me personally?  No I don't personally have much experience with
tensorflow.  There are also many different ways that you might use them
together, so one tutorial might not serve your exact needs.
