### ISSUE TITLE
Needs new PyPI release after merge of PR #4

### ISSUE THREAD

**Issue by n8henrie** [mrocklin/dask-tensorflow#5]
Getting the "requirements.txt" error fixed by https://github.com/dask/dask-tensorflow/pull/4 when installing `pip install dask-tensorflow`, which also breaks `pip install dask-ml[tensorflow]`. Downloading the tarfile from PyPI shows it still doesn't contain a `requirements.txt`, so I think you just need to re-release to PyPI.

In the meantime, `pip install git+https://github.com/dask/dask-tensorflow` works.

**Comment by mrocklin** [comment]
I've updated the version and pushed to PyPI.  Thank you for the message @n8henrie !
