### ISSUE TITLE
ImportError: cannot import name 'Queue' from 'distributed.compatibility'

### ISSUE THREAD

**Issue by dhairyasheelsutar** [mrocklin/dask-tensorflow#8]
I am using dask_tensorflow but its giving me this error

**Comment by TomAugspurger** [comment]
This is after https://github.com/dask/distributed/pull/2896.

It just needs to be `from queue import Queue`.

**Comment by dhairyasheelsutar** [comment]
Cool

**Comment by rkiwanuka** [comment]
I'm still getting this error. What should I do?

**Comment by rkiwanuka** [comment]
I've tried installing directly from github with the following:

$ conda activate mapping
$ conda install git pip
$ pip install git+git://github.com/dask/dask-tensorflow@master

this however causes various import issues when I try to import dask_tensorflow. 

I can see that the although the import statement "from distributed.compatibility import Queue" has been updated on github, it is not updated in the package available from https://pypi.org/project/dask-tensorflow/ (pip install dask-tensorflow) or from https://anaconda.org/conda-forge/dask-tensorflow (conda install -c conda-forge dask-tensorflow)

I would be grateful if I could get the fix through either pip or conda.

**Comment by TomAugspurger** [comment]
It'll be a while before I can prioritize a release. Installing from github
is your best option for now.

**Comment by mrocklin** [comment]
It's worth noting that this library is not actively maintained.  It also
doesn't do anything particularly useful.

**Comment by birds544** [comment]
Hi! 
I'm getting the same error when I try to install dask_tensorflow. 
@TomAugspurger -I tried the github install route as well. I'm still getting this error: 

ImportError: cannot import name 'Queue' from 'distributed.compatibility'

@mrocklin:
I don't understand why you say this library doesn't do anything particularly useful.
Isn't Dask Tensorflow (https://ml.dask.org/tensorflow.html) one of the big promises of Dask? If Dask Tensorflow cannot even be installed, you should simply remove it from your website. That way, unwitting developers like myself don't waste hours of our time trying to get it to work. 

Either that- or please get a Dask Tensorflow release soon-- one that can be installed!!

**Comment by TomAugspurger** [comment]
PRs to remove that documentation page would be welcome. I believe the source is in the dask-ml repo.

**Comment by birds544** [comment]
So you don't intend to release an installable Dask -tensorflow soon?

**Comment by TomAugspurger** [comment]
No plans right now.
